window.xuanzetiJson = [
"1.-Could I borrow your car, please?",
"-______________________",
"A.Good idea.",
"B.No hurry.",
"C.With pleasure.",
"D.No surprise.",
"答案：C",
"2.- It's rather cold in here. Do you mind if I close the window?",
"- ________ ",
"A.Yes, please.",
"B.No, please.",
"C.Sure, please.",
"D.I don't like it.",
"答案：B",
"3.- What's the problem with your bike?",
"- _________ ",
"A.Not at all.",
"B.Good, thank you.",
"C.Nothing serious.",
"D.Sure",
"答案：C",
"4.- How's your family?",
"- _________ ",
"A.Thanks all the same.",
"B.Thanks for calling.",
"C.Not too bad.",
"D.Don't mention it.",
"答案：C",
"5.- Hi, Tom, how's everything with you? ",
"- ___________, and how are you?",
"A.Don't mention it",
"B.Hm, not too bad",
"C.Thanks",
"D.Pretty fast",
"答案：B",
"1.- I'm going to Beijing next week, you know it's one of the most beautiful cities in China.",
"- _____________________",
"A.Enjoy yourself",
"B.It's a pleasure",
"C.Good luck",
"D.very good",
"答案：A",
"2.- Congratulations! You won the first prize in today's speech contest.",
"- ________ ",
"A.Yes, I beat the others.",
"B.No, no, I didn't do it well.",
"C.Thank you.",
"D.It's a pleasure.",
"答案：C",
"3.- Do you mind my smoking here?",
"- _______ ",
"A.No, thanks.",
"B.Yes, I do.",
"C.Yes. I'd rather not.",
"D.Good idea.",
"答案：B",
"4.- Good morning, may I speak to Mark, please?",
"- _________ ",
"A.Who's there?",
"B.Who's that speaking?",
"C.Who are you?",
"D.Who wants to speak to Mark?",
"答案：B",
"5.- Thank you for calling.",
"- _________ ",
"A.Don't mention it.",
"B.That's fine.",
"C.Nice talking to you.",
"D.Call back again.",
"答案：C",
"1.-Could I borrow your car, please?",
"-______________________",
"A.Good idea.",
"B.No hurry.",
"C.With pleasure.",
"D.No surprise.",
"答案：C",
"2.- Is it possible for you to work late tonight?     ",
"- _______ ",
"A.I like it.",
"B.I'll do that.",
"C.I'd love to.",
"D.I think so.",
"答案：D",
"3.- Thank you for your invitation.",
"- _________ ",
"A.It doesn't matter.",
"B.It's a pleasure.",
"C.It's a small thing.",
"D.I'll appreciate it.",
"答案：B",
"4.- Good morning, John. How are you doing?",
"- _________ ",
"A.I'm pleased.",
"B.Good night.",
"C.Not so bad. And you?",
"D.How do you do?",
"答案：C",
"5.- Excuse me, how much is the jacket? ",
"- It's 499 Yuan. ________",
"A.Oh, no. That's OK!",
"B.How do you like it?",
"C.Which do you prefer?",
"D.Would you like to try it on?",
"答案：D",
"1.- How much is that meat, please?",
"- _____________________",
"A.Ten o'clock.",
"B.Ten yuan a kilo.",
"C.I like it very much.",
"D.I don't like.",
"答案：B",
"2.- Good morning, may I speak to Mark, please?",
"- _________ ",
"A.Who's there?",
"B.Who's that speaking?",
"C.Who are you?",
"D.Who wants to speak to Mark?",
"答案：B",
"3.- Hi, Tom, how's everything with you? ",
"- ___________, and how are you?",
"A.Don't mention it",
"B.Hm, not too bad",
"C.Thanks",
"D.Pretty fast",
"答案：B",
"4.- Could I borrow your car for a few days?",
"- ________  ",
"A.Yes, you may borrow.",
"B.Yes, go on.",
"C.Sure, here is the key. Enjoy your journey.",
"D.It doesn't matter.",
"答案：C",
"5.- Excuse me, how much is the jacket? ",
"- It's 499 Yuan. ________",
"A.Oh, no. That's OK!",
"B.How do you like it?",
"C.Which do you prefer?",
"D.Would you like to try it on?",
"答案：D",
"1.- What do you do on Sunday?",
"- _______",
"A.I 'm a teacher.     ",
"B.I play football.    ",
"C.You are a student.   ",
"D.They clean rooms.  ",
"答案：B",
"2.- Thank you for calling.",
"- _________ ",
"A.Don't mention it.",
"B.That's fine.",
"C.Nice talking to you.",
"D.Call back again.",
"答案：C",
"3.- What do you think of this novel?",
"- _________ ",
"A.I've read it.",
"B.It's well-written.",
"C.It was written by my uncle.",
"D.I bought it yesterday.",
"答案：B",
"4.- How's your family?",
"- _________ ",
"A.Thanks all the same.",
"B.Thanks for calling.",
"C.Not too bad.",
"D.Don't mention it.",
"答案：C",
"5.- Let's go to the library this afternoon.",
"- _________",
"A.Yes, that's right.",
"B.No. I can't.",
"C.What about you?",
"D.That's a good idea.",
"答案：D",
"1.- Excuse me, when will the 17:15 train arrive? ",
"- _________",
"A.I don't tell you.",
"B.It's been delayed one hour.",
"C.You have to be patient.",
"D.Don't ask me.",
"答案：B",
"2.- Let's go to the library this afternoon.",
"- _________",
"A.Yes, that's right.",
"B.No. I can't.",
"C.What about you?",
"D.That's a good idea.",
"答案：D",
"3.- How's your family?",
"- _________ ",
"A.Thanks all the same.",
"B.Thanks for calling.",
"C.Not too bad.",
"D.Don't mention it.",
"答案：C",
"4.- It's rather cold in here. Do you mind if I close the window?",
"- ________ ",
"A.Yes, please.",
"B.No, please.",
"C.Sure, please.",
"D.I don't like it.",
"答案：B",
"5.- What's the problem with your bike?",
"- _________ ",
"A.Not at all.",
"B.Good, thank you.",
"C.Nothing serious.",
"D.Sure",
"答案：C",
"1.- Shall we sit up here on the grass or down there near the water?",
"- _____",
"A.I'd rather stay here if you don't mind.",
"B.Sorry, I don't like neither.",
"C.Certainly, why not？",
"D.Yes, we like these two places.",
"答案：A",
"2.- Congratulations! You won the first prize in today's speech contest.",
"- ________ ",
"A.Yes, I beat the others.",
"B.No, no, I didn't do it well.",
"C.Thank you.",
"D.It's a pleasure.",
"答案：C",
"3.- How much is this necklace?",
"- _________ ",
"A.It's very nice.",
"B.It's a birthday present from my parents.",
"C.It costs fifty pounds.",
"D.It's a bargain.",
"答案：C",
"4.- Thank you for calling.",
"- _________ ",
"A.Don't mention it.",
"B.That's fine.",
"C.Nice talking to you.",
"D.Call back again.",
"答案：C",
"5.- How are you, Bob? ",
"- ________",
"A.How are you?",
"B.I'm fine. Thank you.",
"C.How do you do?",
"D.Nice to meet you.",
"答案：B",
"1.- Excuse me, but can you tell me the way to the post office？",
"- _____",
"A.Don't ask that.",
"B.Sorry, I'm a stranger here.",
"C.No, I can't say that.",
"D.No, you're driving too fast.",
"答案：B",
"2.- Are you going on holiday for a long time?",
"- _________ ",
"A.It was a long time.",
"B.Two weeks ago.",
"C.No. Only a couple of days.",
"D.Not long time ago.",
"答案：C",
"3.- How's your family?",
"- _________ ",
"A.Thanks all the same.",
"B.Thanks for calling.",
"C.Not too bad.",
"D.Don't mention it.",
"答案：C",
"4.- Good morning, may I speak to Mark, please?",
"- _________ ",
"A.Who's there?",
"B.Who's that speaking?",
"C.Who are you?",
"D.Who wants to speak to Mark?",
"答案：B",
"5.- Is it possible for you to work late tonight?     ",
"- _______ ",
"A.I like it.",
"B.I'll do that.",
"C.I'd love to.",
"D.I think so.",
"答案：D",
"1.- Thank you very much for giving me so much help. ",
"- _____________________.",
"A.No thank you",
"B.You're welcome",
"C.OK",
"D.Thanks",
"答案：B",
"2.- Could you help me with my physics, please？",
"- ________ ",
"A.No, no way.",
"B.No, I couldn't.",
"C.No, I can't.",
"D.Sorry I can't. I have to go to a meeting right now.",
"答案：D",
"3.- Congratulations! You won the first prize in today's speech contest.",
"- ________ ",
"A.Yes, I beat the others.",
"B.No, no, I didn't do it well.",
"C.Thank you.",
"D.It's a pleasure.",
"答案：C",
"4.- How are you, Bob? ",
"- ________",
"A.How are you?",
"B.I'm fine. Thank you.",
"C.How do you do?",
"D.Nice to meet you.",
"答案：B",
"5.- What's the problem with your bike?",
"- _________ ",
"A.Not at all.",
"B.Good, thank you.",
"C.Nothing serious.",
"D.Sure",
"答案：C",
"1.- I believe we've met somewhere before.",
"- No, ____________________. ",
"A.it isn't the same",
"B.it can't be right",
"C.I don't think so",
"D.I'd rather not",
"答案：C",
"2.- What's the problem with your bike?",
"- _________ ",
"A.Not at all.",
"B.Good, thank you.",
"C.Nothing serious.",
"D.Sure",
"答案：C",
"3.- How's your family?",
"- _________ ",
"A.Thanks all the same.",
"B.Thanks for calling.",
"C.Not too bad.",
"D.Don't mention it.",
"答案：C",
"4.- What does Tom's wife do for a living?",
"- _________",
"A.She is a doctor.",
"B.Tom loves his wife.",
"C.She has a happy life.",
"D.She lives far from here.",
"答案：A",
"5.- Wow! This is a marvelous room! I've never known you're so artistic.",
"- ______ ",
"A.Great, I am very art-conscious.",
"B.Don't mention it.",
"C.Thanks for your compliments.",
"D.It's fine.",
"答案：C"]